export enum ReasonTemplateType {
    IMPROVE_FOR_SERVICER = 'improveForServicer',
    IMPROVE_FOR_USER = 'improveForUser',
    CANCEL_DELIVERY_BY_USER = 'cancelDeliveryByUser',
    CANCEL_DELIVERY_INSTALLATION_BY_USER = 'cancelDelInsByUser',
    CANCEL_INSTALLATION_BY_USER = 'cancelInstallationByUser',
    CANCEL_WARRANTY_BY_USER = 'cancelWarrantyByUser',
    FAILURE_PICKUP = 'failurePickup',
    FAILURE_DELIVERY = 'failureDelivery',
    FAILURE_INSTALLATION = 'failureInstallation',
    FAILURE_RETURN = 'failureReturn',
    FAILURE_CONSULT = 'failureConsult',
    REJECT_QUOTATION = 'rejectQuotation',
    CANCEL_BY_HOST = 'cancelByHost',
    CANCEL_BY_RENTER = 'cancelByRenter',
    LATER_PICKUP = 'laterPickup',
    LATER_DELIVERY = 'laterDelivery',
    PENDING_DELIVERY = 'pendingDelivery',
    ATER_RETURN = 'laterReturn',
}