export const environment = {
    production: false,
    accountApiUrl: 'https://api-tms-supra.winmart.vn/api',
    systemApiUrl: 'https://api-tms-supra.winmart.vn/api/admin',
    activityUrl: 'https://api-tms-supra.winmart.vn/activity/api/admin',
    orderApiUrl: 'https://api-tms-supra.winmart.vn/order/api/admin',
    locationApiUrl: 'https://api-tms-supra.winmart.vn/location/api',
    financeApiUrl: 'https://api-tms-supra.winmart.vn/finance/api/admin',
    deliveryApiUrl: 'https://api-tms-supra.winmart.vn/delivery/api/admin',
    authApiUrl: 'https://api-tms-supra.winmart.vn/auth/api/admin',
    marketingApiUrl: 'https://api-tms-supra.winmart.vn/marketing/api/admin',
    wrtrApiUrl: 'https://api-tms-supra.winmart.vn/wrtr/api/admin',
    marketingUrl: 'https://api-tms-supra.winmart.vn/marketing',
    reportUrl: 'https://api-tms-supra.winmart.vn/report/api/admin',
    priceApiUrl: 'https://api-tms-supra.winmart.vn/price/api/admin',
    emailApiUrl: 'https://api-tms-supra.winmart.vn/email/api/admin',
    telecomApiUrl: 'https://api-tms-supra.winmart.vn/telecom/api/admin',
    messengerApiUrl: 'https://api-tms-supra.winmart.vn/messenger/api',
    hookApiUrl: 'https://api-tms-supra.winmart.vn/hook/api/admin',
    warehouseApiUrl: 'https://api-tms-supra.winmart.vn/warehouse/api/admin',
    notificationApiUrl: 'https://api-tms-supra.winmart.vn/notification/api',
    socketUrl: 'wss://api-tms-supra.winmart.vn',
    uploadUrl: 'https://cdn-tms-supra.winmart.vn',
    googleMapsKey: 'AIzaSyBgzLarShvZ84FER16gRADpPBaMbpKuLKQ',
    firebase: {
        apiKey: 'AIzaSyCeuAY72UQv5JetgqqTCHqSubSE_Ibi6m4',
        authDomain: 'etonx-prod.firebaseapp.com',
        databaseURL: 'https://etonx-prod.firebaseio.com',
        projectId: 'etonx-prod',
        storageBucket: 'etonx-prod.appspot.com',
        messagingSenderId: '799919518376',
        appId: '1:799919518376:web:b68742484334bcb75d489d',
        measurementId: 'G-4940G8V96B'
    }
};
