export const environment = {
    production: false,
    accountApiUrl: 'https://apix-dev1.eton.vn/api',
    systemApiUrl: 'https://apix-dev1.eton.vn/api/admin',
    activityUrl: 'https://apix-dev1.eton.vn/activity/api/admin',
    orderApiUrl: 'https://apix-dev1.eton.vn/order/api/admin',
    locationApiUrl: 'https://apix-dev1.eton.vn/location/api',
    financeApiUrl: 'https://apix-dev1.eton.vn/finance/api/admin',
    deliveryApiUrl: 'https://apix-dev1.eton.vn/delivery/api/admin',
    authApiUrl: 'https://apix-dev1.eton.vn/auth/api/admin',
    marketingApiUrl: 'https://apix-dev1.eton.vn/marketing/api/admin',
    wrtrApiUrl: 'https://apix-dev1.eton.vn/wrtr/api/admin',
    marketingUrl: 'https://apix-dev1.eton.vn/marketing',
    reportUrl: 'https://apix-dev1.eton.vn/report/api/admin',
    priceApiUrl: 'https://apix-dev1.eton.vn/price/api/admin',
    emailApiUrl: 'https://apix-dev1.eton.vn/email/api/admin',
    telecomApiUrl: 'https://apix-dev1.eton.vn/telecom/api/admin',
    messengerApiUrl: 'https://apix-dev1.eton.vn/messenger/api',
    hookApiUrl: 'https://apix-dev1.eton.vn/hook/api/admin',
    warehouseApiUrl: 'https://apix-dev1.eton.vn/warehouse/api/admin',
    notificationApiUrl: 'https://apix-dev1.eton.vn/notification/api',
    socketUrl: 'wss://apix-dev1.eton.vn',
    uploadUrl: 'https://uploadx-flex.eton.vn',
    googleMapsKey: 'AIzaSyDSZDsXqqkh-CWptI7fRqWW8t7gBbH2JC8',
    firebase: {
        apiKey: 'AIzaSyBJOW8jjiUeX6KIWZkG6x_SUWA2uykwK9I',
        authDomain: 'etonflexdb.firebaseapp.com',
        databaseURL: 'https://etonflexdb.firebaseio.com',
        projectId: 'etonflexdb',
        storageBucket: 'etonflexdb.appspot.com',
        messagingSenderId: '525087879543',
        appId: '1:525087879543:web:71f0d73bc2d1dcfc703172',
        measurementId: 'G-PS7RCDL3MB'
    }
};
